### Cria um setting
POST {{baseUrl}}{{settingsPath}}
Content-Type: application/json

{
  "chat": "true",
  "username": "admin"
}

### Busca setting para um utilizador
GET {{baseUrl}}{{settingsPath}}/admin
Content-Type: application/json

### Atualiza setting para um utilizador
PUT {{baseUrl}}{{settingsPath}}/admin
Content-Type: application/json

{
  "chat": "true"
}

###
